### ISSUE TITLE
Upgrade to Maven 3.3.9

### ISSUE THREAD

**Issue by ctrimble** [totem/java-oracle-base#1]
Update maven to `3.3.9` and provide a clear way to update the version in the future.

This script will do the update:

```
sudo apt-get purge maven maven2 maven3 --assume-yes
sudo add-apt-repository ppa:andrei-pozolotin/maven3 --assume-yes
sudo apt-get update
sudo apt-get install maven3=3.3.9-001
```

~~I probably need to configure this to pin down the exact version of maven.~~  I am currently unclear on what needs to be done to test and deploy a change to one of the base images.

**Comment by ctrimble** [comment]
The page for this PPA: https://launchpad.net/~andrei-pozolotin/+archive/ubuntu/maven3

**Comment by BobBond** [comment]
Thanks heaps!!! 

FYI: On Ubuntu 14.04.3 LTS server (Standard Azure distribution) the command to add the repository: 

sudo add-apt-repository ppa:andrei-pozolotin/maven3 --assume-yes 

Failed with error: 

add-apt-repository: error: no such option: --assume-yes
cloud@mcserver:/$ sudo add-apt-repository ppa:andrei-pozolotin/maven3
 Maven 3 for Ubuntu.

Removed the switch, all worked fine 

The command to purge existing Maven installs: 
sudo apt-get purge maven maven2 maven3 --assume-yes 

failed with: 
E: Unable to locate package maven3 

Removed the reference, so ran: 
sudo apt-get purge maven maven2 --assume-yes 

and all went fine. Note this didn't halt on (or mention) the '--assume-yes' switch and didn't halt (but mentioned - "Package 'maven' is not installed, so not removed") when it found no Maven v1.x

Thanks again!

**Comment by ctrimble** [comment]
@BobBond Thanks for sharing.

I checked the [manual for add-apt-repository](http://manpages.ubuntu.com/manpages/trusty/man1/add-apt-repository.1.html) and it looks like that command does not have the `--assume-yes` variant of that flag.  You could use `--yes` instead of dropping it.

I also took a look at the [manual for apt-get](http://manpages.ubuntu.com/manpages/trusty/en/man8/apt-get.8.html) and there is a flag for ignoring missing packages (`--ignore-missing`).  Perhaps that will get rid of the warnings you are seeing.
